# Generated by Django 6.0.7 on 2026-07-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_shopsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('damage', 'Damage'), ('loss', 'Loss'), ('return', 'Return'), ('restock', 'Restock'), ('audit', 'Audit'), ('correction', 'Correction'), ('other', 'Other')], max_length=50),
        ),
    ]
