services:
  - type: web
    name: autoparts-billing-api
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn autoparts_billing_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
