-- ========================================================
-- AutoParts Billing - Supabase PostgreSQL Database Schema
-- Run this script in Supabase Dashboard > SQL Editor
-- ========================================================

-- Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sku TEXT UNIQUE,
    category TEXT DEFAULT 'parts',
    price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    stock_qty INTEGER NOT NULL DEFAULT 0,
    low_stock_qty INTEGER NOT NULL DEFAULT 5,
    brand TEXT DEFAULT '',
    description TEXT DEFAULT '',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    vehicle_no TEXT,
    total_visits INTEGER DEFAULT 1,
    total_spent NUMERIC(10,2) DEFAULT 0.00,
    is_premium BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. INVOICES TABLE
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no TEXT UNIQUE NOT NULL,
    customer_name TEXT DEFAULT 'Walk-in Customer',
    customer_phone TEXT DEFAULT '',
    vehicle_no TEXT DEFAULT '',
    payment_method TEXT DEFAULT 'Cash',
    subtotal NUMERIC(10,2) DEFAULT 0.00,
    discount NUMERIC(10,2) DEFAULT 0.00,
    tax NUMERIC(10,2) DEFAULT 0.00,
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    status TEXT DEFAULT 'paid',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. INVOICE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES public.invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    total_price NUMERIC(10,2) NOT NULL DEFAULT 0.00
);

-- 5. STOCK ADJUSTMENTS TABLE
CREATE TABLE IF NOT EXISTS public.stock_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT,
    quantity_change INTEGER NOT NULL,
    reason TEXT NOT NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. SHOP SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.shop_settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    shop_name TEXT DEFAULT 'Putul Auto Parts and Autoscan',
    address TEXT DEFAULT '123 Mechanics Row, Kolkata',
    phone TEXT DEFAULT '+91 98765 43210',
    email TEXT DEFAULT 'contact@putulauto.com',
    printer_ip TEXT DEFAULT '192.168.1.145',
    printer_type TEXT DEFAULT 'thermal'
);

-- Enable Row Level Security (RLS) & Create Public Access Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read/write access on products" ON public.products;
CREATE POLICY "Allow public read/write access on products" ON public.products FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write access on customers" ON public.customers;
CREATE POLICY "Allow public read/write access on customers" ON public.customers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write access on invoices" ON public.invoices;
CREATE POLICY "Allow public read/write access on invoices" ON public.invoices FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write access on invoice_items" ON public.invoice_items;
CREATE POLICY "Allow public read/write access on invoice_items" ON public.invoice_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write access on stock_adjustments" ON public.stock_adjustments;
CREATE POLICY "Allow public read/write access on stock_adjustments" ON public.stock_adjustments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write access on shop_settings" ON public.shop_settings;
CREATE POLICY "Allow public read/write access on shop_settings" ON public.shop_settings FOR ALL USING (true) WITH CHECK (true);

-- Seed Default Shop Settings
INSERT INTO public.shop_settings (id, shop_name, address, phone, email, printer_ip, printer_type)
VALUES (1, 'Putul Auto Parts and Autoscan', '123 Mechanics Row, Kolkata', '+91 98765 43210', 'contact@putulauto.com', '192.168.1.145', 'thermal')
ON CONFLICT (id) DO NOTHING;

-- Seed Sample Products
INSERT INTO public.products (id, name, sku, price, stock_qty, low_stock_qty, category, brand, description)
VALUES 
(1, 'Brake Pad Set - Front', 'BP-9921', 1250, 14, 5, 'parts', 'OEM', 'High-friction pads for heavy-duty SUVs.'),
(2, 'Oil Filter - Synthetic', 'OF-4402', 450, 8, 5, 'fluids', 'K&N', 'Premium synthetic media oil filter.'),
(3, 'Ceramic Brake Pads', 'CBP-7812', 2450, 2, 5, 'parts', 'Brembo', 'High-performance ceramic brake pads.'),
(4, 'Platinum Battery 12V', 'BAT-750', 8500, 24, 3, 'parts', 'Bosch', '750 CCA, Maintenance-free lead-acid.'),
(5, 'Iridium Spark Plug', 'SPK-0022', 780, 148, 20, 'parts', 'NGK', 'Long-lasting ignition for performance engines.')
ON CONFLICT (id) DO NOTHING;

-- Seed Sample Customers
INSERT INTO public.customers (id, name, phone, vehicle_no, total_visits, total_spent, is_premium)
VALUES
(1, 'John Cooper', '9876543210', 'WB-01-AB-1234', 5, 12500, true),
(2, 'City Motors', '8765432109', 'WB-02-CD-5678', 12, 45000, true),
(3, 'Sarah Miller', '7654321098', 'WB-03-EF-9012', 3, 3200, false)
ON CONFLICT (id) DO NOTHING;

-- Fix Primary Key Sequences for Auto-Increment
SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE((SELECT MAX(id) FROM public.products), 1));
SELECT setval(pg_get_serial_sequence('public.customers', 'id'), COALESCE((SELECT MAX(id) FROM public.customers), 1));
SELECT setval(pg_get_serial_sequence('public.invoices', 'id'), COALESCE((SELECT MAX(id) FROM public.invoices), 1));
SELECT setval(pg_get_serial_sequence('public.invoice_items', 'id'), COALESCE((SELECT MAX(id) FROM public.invoice_items), 1));
SELECT setval(pg_get_serial_sequence('public.stock_adjustments', 'id'), COALESCE((SELECT MAX(id) FROM public.stock_adjustments), 1));

