/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./www/**/*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#000767',
        'on-surface-variant': '#454652',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e1e3e4',
        'surface-container-highest': '#e1e3e4',
        'surface-container': '#edeeef',
        'on-tertiary-fixed': '#341100',
        'surface': '#f8f9fa',
        'error-container': '#ffdad6',
        'on-secondary-container': '#526772',
        'surface-container-high': '#e7e8e9',
        'on-primary-fixed-variant': '#343d96',
        'tertiary-container': '#542000',
        'inverse-on-surface': '#f0f1f2',
        'surface-bright': '#f8f9fa',
        'error': '#ba1a1a',
        'secondary-container': '#cfe6f2',
        'background': '#f8f9fa',
        'tertiary': '#331000',
        'surface-dim': '#d9dadb',
        'primary-container': '#1a237e',
        'outline': '#767683',
        'secondary': '#4c616c',
        'secondary-fixed-dim': '#b4cad6',
        'inverse-primary': '#bdc2ff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'secondary-fixed': '#cfe6f2',
        'tertiary-fixed-dim': '#ffb691',
        'on-background': '#191c1d',
        'primary': '#000666',
        'outline-variant': '#c6c5d4',
        'on-secondary-fixed': '#071e27',
        'inverse-surface': '#2e3132',
        'on-tertiary-fixed-variant': '#793100',
        'on-error-container': '#93000a',
        'surface-tint': '#4c56af',
        'on-surface': '#191c1d',
        'tertiary-fixed': '#ffdbcb',
        'on-primary': '#ffffff',
        'on-primary-container': '#8690ee',
        'primary-fixed': '#e0e0ff',
        'surface-container-low': '#f3f4f5',
        'on-secondary-fixed-variant': '#354a53',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#bdc2ff',
        'on-tertiary-container': '#fa6d00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        'lg': '24px',
        'gutter': '24px',
        'base': '4px',
        'xl': '32px',
        'sm': '8px',
        'md': '16px',
        'xs': '4px',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
